# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/888/bin/cmake

# The command to remove a file.
RM = /snap/cmake/888/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robert/classes/csci1951l/rathDB_stencil

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robert/classes/csci1951l/rathDB_stencil

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/cmake/888/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/cmake/888/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/888/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/snap/cmake/888/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/cmake/888/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/cmake/888/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/888/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/cmake/888/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/cmake/888/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robert/classes/csci1951l/rathDB_stencil/CMakeFiles /home/robert/classes/csci1951l/rathDB_stencil//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robert/classes/csci1951l/rathDB_stencil/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named proto

# Build rule for target.
proto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 proto
.PHONY : proto

# fast build rule for target.
proto/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/proto.dir/build.make core/CMakeFiles/proto.dir/build
.PHONY : proto/fast

#=============================================================================
# Target rules for targets named crypto

# Build rule for target.
crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crypto
.PHONY : crypto

# fast build rule for target.
crypto/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/crypto.dir/build.make core/CMakeFiles/crypto.dir/build
.PHONY : crypto/fast

#=============================================================================
# Target rules for targets named rathDB

# Build rule for target.
rathDB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rathDB
.PHONY : rathDB

# fast build rule for target.
rathDB/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/rathDB.dir/build.make core/CMakeFiles/rathDB.dir/build
.PHONY : rathDB/fast

#=============================================================================
# Target rules for targets named db

# Build rule for target.
db: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 db
.PHONY : db

# fast build rule for target.
db/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/db.dir/build.make core/CMakeFiles/db.dir/build
.PHONY : db/fast

#=============================================================================
# Target rules for targets named primitives

# Build rule for target.
primitives: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 primitives
.PHONY : primitives

# fast build rule for target.
primitives/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/primitives.dir/build.make core/CMakeFiles/primitives.dir/build
.PHONY : primitives/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googlemock/CMakeFiles/gmock.dir/build.make googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest-build/googletest/CMakeFiles/gtest.dir/build.make googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named test_chain_writer

# Build rule for target.
test_chain_writer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_chain_writer
.PHONY : test_chain_writer

# fast build rule for target.
test_chain_writer/fast:
	$(MAKE) $(MAKESILENT) -f test/chain_writer/CMakeFiles/test_chain_writer.dir/build.make test/chain_writer/CMakeFiles/test_chain_writer.dir/build
.PHONY : test_chain_writer/fast

#=============================================================================
# Target rules for targets named test_db

# Build rule for target.
test_db: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_db
.PHONY : test_db

# fast build rule for target.
test_db/fast:
	$(MAKE) $(MAKESILENT) -f test/db/CMakeFiles/test_db.dir/build.make test/db/CMakeFiles/test_db.dir/build
.PHONY : test_db/fast

#=============================================================================
# Target rules for targets named test_crypto

# Build rule for target.
test_crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_crypto
.PHONY : test_crypto

# fast build rule for target.
test_crypto/fast:
	$(MAKE) $(MAKESILENT) -f test/crypto/CMakeFiles/test_crypto.dir/build.make test/crypto/CMakeFiles/test_crypto.dir/build
.PHONY : test_crypto/fast

#=============================================================================
# Target rules for targets named test_primitives

# Build rule for target.
test_primitives: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_primitives
.PHONY : test_primitives

# fast build rule for target.
test_primitives/fast:
	$(MAKE) $(MAKESILENT) -f test/primitives/CMakeFiles/test_primitives.dir/build.make test/primitives/CMakeFiles/test_primitives.dir/build
.PHONY : test_primitives/fast

#=============================================================================
# Target rules for targets named test_block_info_database

# Build rule for target.
test_block_info_database: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_block_info_database
.PHONY : test_block_info_database

# fast build rule for target.
test_block_info_database/fast:
	$(MAKE) $(MAKESILENT) -f test/block_info_database/CMakeFiles/test_block_info_database.dir/build.make test/block_info_database/CMakeFiles/test_block_info_database.dir/build
.PHONY : test_block_info_database/fast

#=============================================================================
# Target rules for targets named test_coin_database

# Build rule for target.
test_coin_database: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_coin_database
.PHONY : test_coin_database

# fast build rule for target.
test_coin_database/fast:
	$(MAKE) $(MAKESILENT) -f test/coin_database/CMakeFiles/test_coin_database.dir/build.make test/coin_database/CMakeFiles/test_coin_database.dir/build
.PHONY : test_coin_database/fast

#=============================================================================
# Target rules for targets named test_chain

# Build rule for target.
test_chain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_chain
.PHONY : test_chain

# fast build rule for target.
test_chain/fast:
	$(MAKE) $(MAKESILENT) -f test/chain/CMakeFiles/test_chain.dir/build.make test/chain/CMakeFiles/test_chain.dir/build
.PHONY : test_chain/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... crypto"
	@echo "... db"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... primitives"
	@echo "... proto"
	@echo "... rathDB"
	@echo "... test_block_info_database"
	@echo "... test_chain"
	@echo "... test_chain_writer"
	@echo "... test_coin_database"
	@echo "... test_crypto"
	@echo "... test_db"
	@echo "... test_primitives"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

